// src/components/ImagesCarousel.svelte
<script>
    import { Navigation, A11y } from 'swiper';

    import { Swiper, SwiperSlide } from 'swiper/svelte';
    import 'swiper/css';
    import 'swiper/css/navigation';

    export let images = [];
    export let classes = "";
</script>

  <Swiper
    modules={[Navigation, A11y]}
    spaceBetween={28}
    slidesPerView={3}
    navigation
    class="{classes} images-carousel"
  >
  {#each images as image}
    <SwiperSlide class="images-carousel-item">
      <img src={image} alt="" />
    </SwiperSlide>
  {/each}
  </Swiper>

// components/imagesCarousel.vue
<template>
  <div class="swiper-container">
    <div class="swiper-button-next"></div>
    <div class="swiper-button-prev"></div>
    <div
      class="swiper"
      v-swiper:mySwiper="swiperOptions"
    >
      <div :class="`${classes} swiper-wrapper images-carousel`">
        <div class="swiper-slide images-carousel-item" v-for="image, index in images" :key="index">
          <img src="@/assets/images/rod.png" alt="brands">
        </div>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  props: {
    images: Array,
    classes: String,
  },
  data() {
    return {
      swiperOptions: {
        loop: true,
        slidesPerView: 3,
        spaceBetween: 50,
        navigation: {
          nextEl: '.swiper-button-next',
          prevEl: '.swiper-button-prev'
        }
      },
    }
  }
}
</script>
