// src/components/stuffs/Stuffs.svelte
<script>
  import { Navigation } from 'swiper';

  import { Swiper, SwiperSlide } from 'swiper/svelte';
  import 'swiper/css';
  import 'swiper/css/navigation';

  import StuffsList from './StuffsList.svelte';

  import AbugarciaIcon from '../../assets/images/brands/AbuGarcia.png';
  import DIcon from '../../assets/images/brands/D.png';
  import JackallIcon from '../../assets/images/brands/Jackall.png';
  import ShimanoIcon from '../../assets/images/brands/Shimano.png';
  import SunlineIcon from '../../assets/images/brands/Sunline.png';
  import RodImage from '../../assets/images/rod.png';
  import StuffsSort from './StuffsSort.svelte';

  const sliderElements = [
    AbugarciaIcon,
    DIcon,
    JackallIcon,
    ShimanoIcon,
    SunlineIcon,
  ];

  let options = [
    {id: 1, value: 'val'},
    {id: 2, value: 'val'},
    {id: 3, value: 'val'},
    {id: 4, value: 'val'},
    {id: 5, value: 'val'},
    {id: 6, value: 'val'},
    {id: 7, value: 'val'},
    {id: 8, value: 'val'},
  ];

  let stuffs = [
    {
      id: 1,
      image: RodImage,
      title: 'Удилище',
      price: '7999',
    },
    {
      id: 2,
      image: RodImage,
      title: 'Удилище',
      price: '13999',
    },
    {
      id: 3,
      image: RodImage,
      title: 'Удилище',
      price: '13999',
    },
    {
      id: 4,
      image: null,
      title: 'Удилище',
      price: '13999',
    },
  ];

</script>

<div class="stuffs-wrapper">
  <!-- todo: swiper styles are broken, try add more swiper sldies and then you'll see -->
  <div class="swiper-container">
    <div class="swiper-button-next"></div>
    <div class="swiper-button-prev"></div>
    <Swiper
      modules={[Navigation]}
      spaceBetween={55}
      slidesPerView={5}
      loop={true}
      navigation={{
        nextEl: '.swiper-button-next',
        prevEl: '.swiper-button-prev'
      }}
      class="stuffs-brands"
    >
    
      {#each sliderElements as slide, index}
        <SwiperSlide class="swiper-slide-item">
          <img id={"slide" + index} src={slide} alt="" />
        </SwiperSlide>
      {/each}
      
    </Swiper>

  </div>

  <StuffsSort types={options} />
  <StuffsList stuffs={stuffs} />
</div>

<style> 
</style>

// components/stuffs/Stuffs.vue
<template>
  <div class="stuffs-wrapper">
    <div class="swiper-container">
      <div class="swiper-button-next"></div>
      <div class="swiper-button-prev"></div>
      <div
        class="swiper stuffs-brands"
        v-swiper:mySwiper="swiperOptions"
      >
        <div class="swiper-wrapper">
          <div class="swiper-slide swiper-slide-item" v-for="slide,index in sliderElements" :key="slide">
            <img :id="index" :src="require(`@/assets/images/brands/${slide}`)" alt="brands">
          </div>
        </div>
        <div class="swiper-pagination swiper-pagination-bullets"></div> 
      </div>
    </div>
    <StuffsSort />
    <StuffsList :stuffs="stuffs" />
  </div>
</template>

<script>
import StuffsSort from '@/components/stuffs/StuffsSort'
import StuffsList from '@/components/stuffs/StuffsList'

  export default {
      name: 'swiper-nuxt',
      directives: {
    },
    components: {
      StuffsSort,
      StuffsList
    },
    data () {
      return {
        swiperOptions: {
          loop: true,
          slidesPerView: 5,
          spaceBetween: 50,
          navigation: {
            nextEl: '.swiper-button-next',
            prevEl: '.swiper-button-prev'
          }
        },
        sliderElements: [
          'AbuGarcia.png',
          'D.png',
          'Jackall.png',
          'Shimano.png',
          'Sunline.png'
        ],
        stuffs: [
          {
            id: 1,
            image: 'rod.png',
            title: 'Удилище',
            price: '7999',
          },
          {
            id: 2,
            image: 'rod.png',
            title: 'Удилище',
            price: '13999',
          },
          {
            id: 3,
            image: 'rod.png',
            title: 'Удилище',
            price: '13999',
          },
          {
            id: 4,
            image: 'rod.png',
            title: 'Удилище',
            price: '13999',
          },
        ],
      }
    },
    methods: {
    },
  }
</script>

<style lang="scss" scoped>

</style>
